toml
# In gradle/libs.versions.toml

[versions]
# ... (your existing versions like agp, kotlin, etc.)

[libraries]
# ... (your existing libraries)

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Add the following line for KAPT
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
